apiVersion: v1
kind: Service
metadata:
  name: {{ include "external-service.fullname" . }}
  labels:
    {{- include "external-service.labels" . | nindent 4 }}
spec:
 type: ClusterIP
 ports:
 - port: {{ .Values.service.port }}
   targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "external-service.fullname" . }}
subsets:
  - addresses:
      {{- range .Values.service.ips }}
      - ip: {{ . }}
      {{- end }}
    ports:
      - port: {{ .Values.service.port }} # 5672