apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
    name: {{ include "webserver.fullname" . }}-identity-binding
spec:
    azureIdentity: {{ .Values.azureIdentityName }}
    selector: {{ include "webserver.bindingselector" . }}