apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
    name: {{ include "webserver.fullname" . }}-{{ .Release.Namespace }}-identity-binding
    namespace: platform
spec:
    azureIdentity: {{ .Values.azureIdentityName }}
    selector: {{ include "webserver.bindingselector" . }}