apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "webserver.secretprovider" . }}
spec:
  provider: azure
  {{- with .Values.secretObjects }}
  secretObjects:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  parameters:
    usePodIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: {{ .Values.keyvaultName }}
    objects: |
      array:
        {{- range .Values.secrets }}
        - |
          objectName: {{ .name | quote }}
          objectType: {{ .type | quote }}
          {{ if .encoding }}objectEncoding: {{ .encoding | quote }}{{ end }}
        {{- end }}
    resourceGroup: {{ .Values.resourceGroup }}
    subscriptionId: {{ .Values.subscriptionId }}
    tenantId: {{ .Values.tenantId }}
