apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "secret-provider.fullname" . }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: {{ .Values.keyvaultName }}
    objects: |
      array:
        {{- range .Values.secrets }}
        - |
          objectName: {{ .name }}
          objectType: {{ .type }}
        {{- end }}
    resourceGroup: {{ .Values.resourceGroup }}
    subscriptionId: {{ .Values.subscriptionId }}
    tenantId: {{ .Values.tenantId }}
